# -*- coding: utf-8 -*-
"""HFModel_1021043.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AAKMs7G5uO6zTSa0g5aAxoEEGLVcseIS
"""

#Text to image generator
#Change runtime type to GPU

!pip install transformers accelerate diffusers invisible_watermark safetensors

from diffusers import DiffusionPipeline
import torch
from PIL import Image
import matplotlib.pyplot as plt

# Load the model
pipe = DiffusionPipeline.from_pretrained(
    "stabilityai/stable-diffusion-xl-base-1.0",
    torch_dtype=torch.float16,
    use_safetensors=True,
    variant="fp16"
)
pipe.to("cuda")

#Define a function to generate and display images based on text prompts
def generate_and_display_image(prompt):
    # Generate the image
    images = pipe(prompt=prompt).images[0]

    # Display the image
    plt.imshow(images)
    plt.axis('off')  # Hide the axis
    plt.show()

# Example
prompt = "An astronaut riding a green horse"
generate_and_display_image(prompt)

new_prompt = "A cartoon girl wearing a pink dress standing on one foot"
generate_and_display_image(new_prompt)

new_prompt2 = "seashells on the beach"
generate_and_display_image(new_prompt2)

new_prompt3 = "drawing of sunset over the city"
generate_and_display_image(new_prompt3)